# Generated by Django 3.2 on 2022-06-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_userdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
