# Generated by Django 4.0.5 on 2022-06-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_delete_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
